# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Starbucks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starbucks
  pod 'SwiftLint'
  target 'StarbucksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarbucksUITests' do
    # Pods for testing
  end

end
